on: push
name: Test SFTP Deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action-Typescript@master
      with:
        # deploy to a folder named "sftp-deploy-test.samkirkland.com" on my server
        # sftp://ftp.samkirkland.com:7822/home/samkirkland/sftp-deploy-test.samkirkland.com/  
        ftp-server: ${{ secrets.ftp_server }}
        ftp-username: ${{ secrets.sftp_username }}
        ftp-password: ${{ secrets.sftp_password }}
        git-ftp-args: --insecure
        git-ftp-command: push  
